server:
  port: 8082

spring:
  application:
    name: processing-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        enable.idempotence: true
    consumer:
      group-id: processing-service
      auto-offset-reset: earliest
      enable-auto-commit: false           # manual ack -> commit AFTER downstream publish
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.coresys.common.events
        spring.json.value.default.type: com.coresys.common.events.TransactionEvent
    listener:
      ack-mode: MANUAL

features:
  async:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
